import{useEffect,useState}from'react';
import{Link,useLocation}from'react-router-dom';
import{motion}from'framer-motion';
import{ArrowRight,Building2,Check,ChevronDown,Clock3,Coffee,MapPin,Monitor,Phone,ShieldCheck,Users,Wifi,X,Zap}from'lucide-react';
import{api,money}from'../api';
import{Empty,Loading}from'../components/Layout';
import{WorkspaceCard}from'../components/WorkspaceCard';
import{useApp}from'../context';
import{useSiteContent}from'../siteContent';

const reveal={initial:{opacity:0,y:24},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.15},transition:{duration:.65,ease:[.16,1,.3,1]}};
const faqs=[
 ['How do I book?','Choose a workspace and time, select one or more available seats, sign in, and confirm your booking.'],
 ['Can I cancel?','You can request cancellation until 48 hours before the booking starts. The admin team will review it.'],
 ['Does the price include GST?','Before you confirm, the summary clearly shows the workspace price and GST separately.'],
 ['Can I book for my team?','Yes. Private cabins, meeting rooms and the conference room can be booked for teams.']
];
const proofItems=[
 [Building2,'3, 4 & 6-seater cabins','Private spaces for growing teams'],
 [Clock3,'Hourly to monthly','Choose the booking plan you need'],
 [ShieldCheck,'Yearly lease support','Request a call without an account']
];
const initialForm={name:'',mobile:'',email:'',company:'',workspaceType:'not_sure',seats:'',preferredDate:'',message:'',consent:false};
const typeLabel=value=>({hot_desk:'Hot desk',dedicated_desk:'Dedicated desk',private_cabin:'Private cabin',meeting_room:'Meeting room',conference_room:'Conference room',phone_booth:'Phone booth'})[value]||'Workspace';
const unitLabel=value=>({hourly:'hour',daily:'day',weekly:'week',monthly:'month'})[value]||value;
const priceOf=item=>{const order=['hourly','daily','weekly','monthly'],unit=order.find(key=>item?.pricing?.[key]);return unit?{unit,amount:item.pricing[unit]}:null};

export default function Home(){
 const content=useSiteContent('home',{title:'A better workspace for your best work.',body:'Private cabins and professional meeting spaces on Bannerghatta Main Road—with clear booking choices and live availability.'});
 const[workspaces,setWorkspaces]=useState([]),[loading,setLoading]=useState(true),[form,setForm]=useState(initialForm),[busy,setBusy]=useState(false),[sent,setSent]=useState(false),[showEnquiry,setShowEnquiry]=useState(false),[priceItem,setPriceItem]=useState(null),{toast}=useApp(),location=useLocation();
 useEffect(()=>{document.title='TWS — Workspaces on Bannerghatta Main Road';api('/workspaces').then(result=>setWorkspaces((result.items||[]).filter(item=>item.status==='active'))).catch(error=>toast(error.message,'error')).finally(()=>setLoading(false))},[]);
 useEffect(()=>{if(location.hash)requestAnimationFrame(()=>document.querySelector(location.hash)?.scrollIntoView({behavior:'smooth',block:'start'}))},[location.hash]);
 useEffect(()=>{const open=showEnquiry||priceItem;if(open)document.body.style.overflow='hidden';const close=event=>{if(event.key==='Escape'){setShowEnquiry(false);setPriceItem(null)}};window.addEventListener('keydown',close);return()=>{document.body.style.overflow='';window.removeEventListener('keydown',close)}},[showEnquiry,priceItem]);
 async function enquire(event){event.preventDefault();setBusy(true);try{const payload={...form,seats:form.seats?Number(form.seats):undefined,preferredDate:form.preferredDate||undefined};await api('/enquiries',{method:'POST',body:JSON.stringify(payload)});setSent(true);setForm(initialForm);setShowEnquiry(false);toast('Enquiry sent. Our team will call you shortly.')}catch(error){toast(error.message,'error')}finally{setBusy(false)}}
 const set=event=>setForm(value=>({...value,[event.target.name]:event.target.type==='checkbox'?event.target.checked:event.target.value})),pricing=workspaces.filter(item=>priceOf(item)).slice(0,3);
 return <div className="simple-home">
  <section className="simple-hero"><div className="simple-hero-motion" aria-hidden="true"><img src="/images/tws-foyer-01.webp" alt=""/><i/><b/></div><div className="simple-hero-shade"/><motion.div className="simple-hero-copy" initial={{opacity:0,y:28}} animate={{opacity:1,y:0}} transition={{duration:.85,ease:[.16,1,.3,1]}}><span className="hero-location"><MapPin/> Bannerghatta Main Road · South Bengaluru</span><h1>{content.title}</h1><p>{content.body}</p><div className="simple-hero-actions"><Link className="btn btn-accent" to="/book">Check available spaces <ArrowRight/></Link><button className="btn btn-glass" onClick={()=>setShowEnquiry(true)}>Request a purchase call</button></div></motion.div><div className="simple-proof"><div className="simple-proof-track">{proofItems.map(([Icon,title,copy])=><span key={title}><Icon/><b>{title}</b><small>{copy}</small></span>)}</div></div></section>

  <motion.section className="home-intro home-section" {...reveal}><div><p className="eyebrow">The Work Suites</p><h2>Everything you need,<br/><em>without the confusion.</em></h2></div><div><p>Choose a flexi desk, dedicated desk, private cabin, meeting room or 22+1-seat conference room. Two private phone booths are included as an amenity and are not charged separately.</p><Link className="text-link" to="/about">Learn about TWS <ArrowRight/></Link></div></motion.section>

  <section className="home-spaces home-section" id="spaces"><motion.header className="home-section-head" {...reveal}><div><p className="eyebrow">Choose your space</p><h2>One place. <em>Many ways to work.</em></h2></div><Link className="text-link" to="/workspaces">See all spaces <ArrowRight/></Link></motion.header>{loading?<Loading cards={4}/>:workspaces.length?<div className="home-space-grid">{workspaces.slice(0,4).map((item,index)=><WorkspaceCard item={item} index={index} key={item._id}/>)}</div>:<Empty title="Workspaces are being prepared"/>}</section>

  <section className="home-pricing home-section" id="pricing"><motion.header className="home-section-head" {...reveal}><div><p className="eyebrow">Clear prices</p><h2>Know the price<br/><em>before you book.</em></h2></div><Link className="text-link" to="/pricing">See full pricing <ArrowRight/></Link></motion.header>{loading?<Loading cards={3}/>:<div className="home-price-grid">{pricing.map((item,index)=>{const price=priceOf(item);return <motion.button {...reveal} transition={{...reveal.transition,delay:index*.08}} key={item._id} onClick={()=>setPriceItem(item)}><span>{typeLabel(item.type)}</span><h3>{item.name}</h3><strong>{money(price.amount)}<small> / {unitLabel(price.unit)}</small></strong><p>Click to see all prices and what is included.</p><i>View price details <ArrowRight/></i></motion.button>})}</div>}</section>

  <section className="easy-steps home-section" id="how-it-works"><motion.header className="home-section-head" {...reveal}><div><p className="eyebrow">How it works</p><h2>Book in <em>three easy steps.</em></h2></div></motion.header><div className="step-cards"><motion.article {...reveal}><span>01</span><h3>Choose a space</h3><p>Compare the room size, facilities and current price.</p></motion.article><motion.article {...reveal}><span>02</span><h3>Choose your plan</h3><p>Book hourly, daily or monthly—or request a yearly lease call.</p></motion.article><motion.article {...reveal}><span>03</span><h3>Confirm your booking</h3><p>Sign in for online checkout, or request a purchase call without an account.</p></motion.article></div></section>

  <section className="home-amenities home-section" id="amenities"><motion.div className="amenities-copy" {...reveal}><p className="eyebrow">Included with your space</p><h2>Come ready to work.<br/><em>We handle the rest.</em></h2><p>The everyday facilities you need are available across TWS.</p><Link className="btn btn-light" to="/amenities">See all facilities <ArrowRight/></Link></motion.div><div className="amenity-grid"><span><Wifi/><b>Fast Wi-Fi</b></span><span><Zap/><b>Power backup</b></span><span><Phone/><b>Two phone booths</b></span><span><Coffee/><b>Coffee & pantry</b></span><span><Users/><b>On-site help</b></span><span><Check/><b>Daily cleaning</b></span></div></section>

  <section className="home-faq home-section" id="faqs"><motion.div {...reveal}><p className="eyebrow">Quick answers</p><h2>Know more<br/><em>before you book.</em></h2><Link className="text-link" to="/faq">See all questions <ArrowRight/></Link></motion.div><div className="faq-list">{faqs.map(([question,answer],index)=><details key={question} open={index===0}><summary>{question}<ChevronDown/></summary><p>{answer}</p></details>)}</div></section>

  <section className="home-enquiry" id="enquire"><div className="enquiry-shell"><motion.div className="enquiry-copy" {...reveal}><p className="eyebrow">Plan a free visit</p><h2>Tell us what<br/><em>you need.</em></h2><p>Share your requirements. Our Bengaluru team will help you choose the right space.</p><div><span><MapPin/> Bannerghatta Main Road · Kothnur, Kalena Agrahara</span><span><Clock3/> Visit timing is confirmed during your callback</span></div></motion.div><EnquiryForm form={form} set={set} enquire={enquire} busy={busy} sent={sent}/></div></section>

  {showEnquiry&&<div className="modal-backdrop public-enquiry-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setShowEnquiry(false)}}><section className="public-enquiry-modal"><header><div><span>TWS</span><div><p>Free site visit</p><h2>Find the right workspace.</h2><small>Send your details and our team will call you.</small></div></div><button onClick={()=>setShowEnquiry(false)} aria-label="Close enquiry form"><X/></button></header><EnquiryForm form={form} set={set} enquire={enquire} busy={busy} compact/></section></div>}
  {priceItem&&<div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setPriceItem(null)}}><section className="price-detail-modal"><button className="modal-close" onClick={()=>setPriceItem(null)} aria-label="Close price details"><X/></button><span className="eyebrow">{typeLabel(priceItem.type)}</span><h2>{priceItem.name}</h2><p>{priceItem.description}</p><div className="price-detail-list">{Object.entries(priceItem.pricing||{}).filter(([unit,value])=>value&&priceItem.allowedDurations?.includes(unit)).map(([unit,value])=><div key={unit}><span>Per {unitLabel(unit)}</span><strong>{money(value)}</strong></div>)}</div><h3>Included</h3><div className="price-amenities">{(priceItem.amenities||[]).map(item=><span key={item}><Check/>{item}</span>)}</div><Link className="btn btn-accent" to={`/book?workspace=${priceItem._id}`}>Check available seats <ArrowRight/></Link></section></div>}
 </div>
}

function EnquiryForm({form,set,enquire,busy,sent=false,compact=false}){const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata'}).format(new Date());return <form className={`enquiry-form ${compact?'compact':''}`} onSubmit={enquire}>{sent&&<div className="enquiry-success"><Check/> Thank you. Your enquiry has been received.</div>}<div className="enquiry-fields"><label>Name<input required name="name" value={form.name} onChange={set} autoComplete="name" placeholder="Your name"/></label><label>Phone number<input required name="mobile" value={form.mobile} onChange={set} autoComplete="tel" inputMode="tel" placeholder="Your phone number"/></label><label>Email<input required type="email" name="email" value={form.email} onChange={set} autoComplete="email" placeholder="you@example.com"/></label><label>Company <small>Optional</small><input name="company" value={form.company} onChange={set} placeholder="Company name"/></label><label>Workspace<select name="workspaceType" value={form.workspaceType} onChange={set}><option value="not_sure">Help me choose</option><option value="hot_desk">Hot / flexi desk</option><option value="dedicated_desk">Dedicated desk</option><option value="private_cabin">Private cabin</option><option value="meeting_room">Meeting room</option><option value="conference_room">Conference room</option><option value="lease">Monthly / yearly lease</option></select></label><label>Seats needed <small>Optional</small><input type="number" min="1" max="100" name="seats" value={form.seats} onChange={set}/></label><label>Visit date <small>Optional</small><input type="date" min={today} name="preferredDate" value={form.preferredDate} onChange={set}/></label><label className={compact?'':'full'}>Message <small>Optional</small><textarea name="message" value={form.message} onChange={set} placeholder="Tell us what you want to purchase or lease…"/></label></div><label className="consent"><input required type="checkbox" name="consent" checked={form.consent} onChange={set}/><span>I agree to receive a call about this enquiry.</span></label><button className="btn btn-accent" disabled={busy}>{busy?'Sending…':'Request a purchase call'} <ArrowRight/></button></form>}
