import{useEffect,useState}from'react';
import{Link,useLocation}from'react-router-dom';
import{motion}from'framer-motion';
import{ArrowRight,Building2,Check,ChevronDown,Clock3,Coffee,MapPin,Phone,ShieldCheck,Wifi,X,Zap}from'lucide-react';
import{api}from'../api';
import{BrandLogo,Empty,Loading}from'../components/Layout';
import{WorkspaceCard}from'../components/WorkspaceCard';
import{useApp}from'../context';
import{useSiteContent}from'../siteContent';

const reveal={initial:{opacity:0,y:24},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.15},transition:{duration:.65,ease:[.16,1,.3,1]}};
const faqs=[
 ['How do I book?','Choose a workspace and time, select one or more available seats, sign in, and confirm your booking.'],
 ['Can I cancel?','You can request cancellation until 48 hours before the booking starts. The admin team will review it.'],
 ['Does the price include GST?','Before you confirm, the summary clearly shows the workspace price and GST separately.'],
 ['Can I book for my team?','Yes. Private cabins, the meeting room and the conference room can be booked for teams.']
];
const initialForm={name:'',mobile:'',email:'',company:'',workspaceType:'not_sure',seats:'',preferredDate:'',message:'',consent:false};
const homeAmenityItems=[[Wifi,'High-speed internet'],[Zap,'24/7 power backup'],[Phone,'Two phone booths'],[Coffee,'Free coffee & vending'],[Check,'Daily cleaning']];
const featuredWorkspaces=items=>{
 const cabin=items.find(item=>item.type==='private_cabin'&&Number(item.capacity)===3)||items.find(item=>item.type==='private_cabin');
 const privateCabin=cabin?{...cabin,name:'Private Cabin',description:'3, 4, 6, 8 and 12-seater options with 24/7 access and 4 complimentary meeting-room hours every month.',bookingWorkspaceId:cabin._id,capacity:3,pricing:{monthly:9999},catalogCabinGroup:true}:null;
 return[items.find(item=>item.type==='hot_desk'),items.find(item=>item.type==='dedicated_desk'),privateCabin,items.find(item=>item.type==='meeting_room'),items.find(item=>item.type==='conference_room')].filter(Boolean);
};

export default function Home(){
 const content=useSiteContent('home',{title:'A better workspace for your best work.',body:'Private cabins and professional meeting spaces on Bannerghatta Main Road—with clear booking choices and live availability.'});
 const[workspaces,setWorkspaces]=useState([]),[loading,setLoading]=useState(true),[form,setForm]=useState(initialForm),[busy,setBusy]=useState(false),[sent,setSent]=useState(false),[showEnquiry,setShowEnquiry]=useState(false),{toast,operationsVersion}=useApp(),location=useLocation();
 useEffect(()=>{document.title='TWS — Workspaces on Bannerghatta Main Road';const timer=setTimeout(()=>{if(!sessionStorage.getItem('tws_enquiry_prompt_seen')){sessionStorage.setItem('tws_enquiry_prompt_seen','1');setShowEnquiry(true)}},2200);return()=>clearTimeout(timer)},[]);
 useEffect(()=>{let active=true;api('/workspaces').then(result=>{if(active)setWorkspaces((result.items||[]).filter(item=>item.status==='active'))}).catch(error=>toast(error.message,'error')).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[operationsVersion]);
 useEffect(()=>{if(location.hash)requestAnimationFrame(()=>document.querySelector(location.hash)?.scrollIntoView({behavior:'smooth',block:'start'}))},[location.hash]);
 useEffect(()=>{if(showEnquiry)document.body.style.overflow='hidden';const close=event=>{if(event.key==='Escape')setShowEnquiry(false)};window.addEventListener('keydown',close);return()=>{document.body.style.overflow='';window.removeEventListener('keydown',close)}},[showEnquiry]);
 async function enquire(event){event.preventDefault();setBusy(true);try{const payload={...form,seats:form.seats?Number(form.seats):undefined,preferredDate:form.preferredDate||undefined};await api('/enquiries',{method:'POST',body:JSON.stringify(payload)});setSent(true);setForm(initialForm);setShowEnquiry(false);toast('Enquiry sent. Our team will call you shortly.')}catch(error){toast(error.message,'error')}finally{setBusy(false)}}
 const set=event=>setForm(value=>({...value,[event.target.name]:event.target.type==='checkbox'?event.target.checked:event.target.value})),homeSpaces=featuredWorkspaces(workspaces),cabins=workspaces.filter(item=>item.type==='private_cabin'),cabinCount=cabins.reduce((sum,item)=>sum+Number(item.bookableUnitCount||0),0),seatWords={3:'three-seater',4:'four-seater',6:'six-seater',8:'eight-seater',12:'twelve-seater'},cabinSummary=cabins.filter(item=>item.bookableUnitCount).map(item=>`${item.bookableUnitCount} ${seatWords[item.capacity]||`${item.capacity}-seater`}`).join(' · '),proofItems=[[Building2,`${cabinCount||21} private cabins`,cabinSummary||'1 three-seater · 13 four-seater · 7 six-seater'],[Clock3,'Hourly to monthly','Choose the booking plan you need'],[ShieldCheck,'Yearly lease support','Request a call without an account']];
 return <div className="simple-home">
  <section className="simple-hero"><div className="simple-hero-motion" aria-hidden="true"><video autoPlay muted loop playsInline preload="metadata"><source src="/videos/tws-workspace-tour.mp4?v=2" type="video/mp4"/></video><i/><b/></div><div className="simple-hero-shade"/><motion.div className="simple-hero-copy" initial={{opacity:0,y:28}} animate={{opacity:1,y:0}} transition={{duration:.85,ease:[.16,1,.3,1]}}><span className="hero-location"><MapPin/> Bannerghatta Main Road · South Bengaluru</span><h1>{content.title}</h1><p>{content.body}</p><div className="simple-hero-actions"><Link className="btn btn-accent" to="/book">Check available spaces <ArrowRight/></Link><button className="btn btn-glass" onClick={()=>setShowEnquiry(true)}>Request a purchase call</button></div></motion.div><div className="simple-proof"><div className="simple-proof-track">{[0,1].map(group=><div className="simple-proof-set" aria-hidden={group===1} key={group}>{proofItems.map(([Icon,title,copy])=><span key={title}><Icon/><b>{title}</b><small>{copy}</small></span>)}</div>)}</div></div></section>

  <motion.section className="home-intro home-section" {...reveal}><div><p className="eyebrow">The Work Suites</p><h2>Everything you need,<br/><em>without the confusion.</em></h2></div><div><p>Private cabins are available in 3, 4, 6, 8 and 12-seater options. Private cabin members receive 4 complimentary meeting-room hours every month. Every workspace includes high-speed internet, two phone booths and complimentary coffee from the vending machine.</p><Link className="text-link" to="/about">Learn more about TWS <ArrowRight/></Link></div></motion.section>

  <section className="home-spaces home-section" id="spaces"><motion.header className="home-section-head" {...reveal}><div><p className="eyebrow">Choose your space</p><h2>One place. <em>Many ways to work.</em></h2></div><Link className="text-link" to="/workspaces">See spaces & prices <ArrowRight/></Link></motion.header>{loading?<Loading cards={5}/>:homeSpaces.length?<div className="home-space-grid">{homeSpaces.map((item,index)=><WorkspaceCard item={item} index={index} key={item._id}/>)}</div>:<Empty title="Workspaces are being prepared"/>}</section>

  <section className="easy-steps home-section" id="how-it-works"><motion.header className="home-section-head" {...reveal}><div><p className="eyebrow">How it works</p><h2>Book in <em>three easy steps.</em></h2></div></motion.header><div className="step-cards"><motion.article {...reveal}><span>01</span><h3>Choose a space</h3><p>Compare the room size, amenities and current price.</p></motion.article><motion.article {...reveal}><span>02</span><h3>Choose your plan</h3><p>Select an available cabin or room, or request a longer lease.</p></motion.article><motion.article {...reveal}><span>03</span><h3>Confirm with TWS</h3><p>Online payment is disabled. The TWS team confirms your booking directly.</p></motion.article></div></section>

  <section className="home-amenities home-section" id="amenities"><motion.div className="amenities-copy" {...reveal}><p className="eyebrow">Amenities included with your space</p><h2>Come ready to work.<br/><em>We handle the rest.</em></h2><p>The everyday amenities you need are included across TWS.</p><Link className="btn btn-light" to="/amenities">Explore all amenities <ArrowRight/></Link></motion.div><div className="amenity-grid">{homeAmenityItems.map(([Icon,title],index)=><motion.span initial={{opacity:0,y:22,scale:.96}} whileInView={{opacity:1,y:0,scale:1}} viewport={{once:true,amount:.35}} transition={{duration:.55,delay:index*.07,ease:[.16,1,.3,1]}} whileHover={{y:-7,scale:1.025}} key={title}><Icon/><b>{title}</b></motion.span>)}</div></section>

  <section className="home-faq home-section" id="faqs"><motion.div {...reveal}><p className="eyebrow">Quick answers</p><h2>Know more<br/><em>before you book.</em></h2><Link className="text-link" to="/faq">See all questions <ArrowRight/></Link></motion.div><div className="faq-list">{faqs.map(([question,answer],index)=><details key={question} open={index===0}><summary>{question}<ChevronDown/></summary><p>{answer}</p></details>)}</div></section>

  <section className="home-enquiry" id="enquire"><div className="enquiry-shell"><motion.div className="enquiry-copy" {...reveal}><p className="eyebrow">Plan a free visit</p><h2>Tell us what<br/><em>you need.</em></h2><p>Share your requirements. Our Bengaluru team will help you choose the right space.</p><div><span><MapPin/> Bannerghatta Main Road, Gottigere, beside Carmel Academy ICSE School, Kothnur, Kalena Agrahara, Bengaluru, Karnataka 560083</span><span><Clock3/> Visit timing is confirmed during your callback</span></div></motion.div><EnquiryForm form={form} set={set} enquire={enquire} busy={busy} sent={sent}/></div></section>

  {showEnquiry&&<div className="modal-backdrop public-enquiry-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setShowEnquiry(false)}}><section className="public-enquiry-modal"><header><div><BrandLogo className="enquiry-brand-logo"/><div><p>Free site visit</p><h2>Find the right workspace.</h2><small>Send your details and our team will call you.</small></div></div><button onClick={()=>setShowEnquiry(false)} aria-label="Close enquiry form"><X/></button></header><EnquiryForm form={form} set={set} enquire={enquire} busy={busy} compact/></section></div>}
 </div>
}

function EnquiryForm({form,set,enquire,busy,sent=false,compact=false}){const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata'}).format(new Date());return <form className={`enquiry-form ${compact?'compact':''}`} onSubmit={enquire}>{sent&&<div className="enquiry-success"><Check/> Thank you. Your enquiry has been received.</div>}<div className="enquiry-fields"><label>Name<input required name="name" value={form.name} onChange={set} autoComplete="name" placeholder="Your name"/></label><label>Phone number<input required name="mobile" value={form.mobile} onChange={set} autoComplete="tel" inputMode="tel" placeholder="Your phone number"/></label><label>Email<input required type="email" name="email" value={form.email} onChange={set} autoComplete="email" placeholder="you@example.com"/></label><label>Company <small>Optional</small><input name="company" value={form.company} onChange={set} placeholder="Company name"/></label><label>Workspace<select name="workspaceType" value={form.workspaceType} onChange={set}><option value="not_sure">Help me choose</option><option value="hot_desk">Hot / flexi desk</option><option value="dedicated_desk">Dedicated desk</option><option value="private_cabin">Private cabin</option><option value="meeting_room">Meeting room</option><option value="conference_room">Conference room</option><option value="lease">Monthly / yearly lease</option></select></label><label>Seats needed <small>Optional</small><input type="number" min="1" max="100" name="seats" value={form.seats} onChange={set}/></label><label>Visit date <small>Optional</small><input type="date" min={today} name="preferredDate" value={form.preferredDate} onChange={set}/></label><label className={compact?'':'full'}>Message <small>Optional</small><textarea name="message" value={form.message} onChange={set} placeholder="Tell us what you want to purchase or lease…"/></label></div><label className="consent"><input required type="checkbox" name="consent" checked={form.consent} onChange={set}/><span>I agree to receive a call about this enquiry.</span></label><button className="btn btn-accent" disabled={busy}>{busy?'Sending…':'Request a purchase call'} <ArrowRight/></button></form>}
