import{useState}from'react';
import{Minus,Plus}from'lucide-react';

const content={
  faq:{title:'Frequently asked questions',intro:'Clear answers before you book.',sections:[['How does booking work?','Choose a workspace and time, hold the inventory, complete payment, and receive your booking confirmation.'],['Can I cancel?','Cancellation requests are accepted until 48 hours before the booking starts. Refund timing depends on the payment method and administrator review.'],['Are prices inclusive of GST?','The booking summary shows the base amount and GST separately before payment.'],['How do refunds work?','Approved refunds are initiated by an administrator through the original payment provider and their status appears in your booking.'],['Can teams book private spaces?','Yes. Private cabins, meeting rooms and the conference room support team reservations.']],},
  privacy:{title:'Privacy policy',intro:'How TWS · The Work Suites handles account and booking information.',sections:[['Information we collect','We store account, contact, billing, booking and payment-reference information needed to operate the service. Card and UPI credentials are handled by the payment provider and are not stored by us.'],['How we use it','Information is used for authentication, reservations, invoices, support, security, service notifications and legal compliance.'],['Retention and security','Access is role-controlled, passwords are salted and hashed, and sensitive operations are audited. Retention periods should be finalized with your legal adviser before launch.'],['Your choices','Customers may update profile information and request account-data assistance through the published support contact.']]},
  terms:{title:'Booking terms',intro:'The operating rules for reservations and workspace use.',sections:[['Reservations','A booking is confirmed only after payment is verified or an authorized operator records an accepted offline payment.'],['Cancellations','Cancellation requests must be submitted at least 48 hours before the booking starts. Final refund rules, deductions and timelines must be published by the business before launch.'],['Workspace use','Customers must follow site safety, access, conduct and acceptable-use rules. Access may be refused for misuse or fraudulent activity.'],['Business details','Company identity, GST registration, legal jurisdiction and contact details must be reviewed and completed before production.']]}
};
function FAQAccordion({items}){const[open,setOpen]=useState(0);return <div className="faq-accordion">{items.map(([title,copy],index)=>{const expanded=open===index;return <article className={expanded?'open':''} key={title}><button onClick={()=>setOpen(expanded?-1:index)} aria-expanded={expanded}><span>{title}</span><i>{expanded?<Minus/>:<Plus/>}</i></button><div className="faq-answer" aria-hidden={!expanded}><p>{copy}</p></div></article>})}</div>}
export default function InfoPage({type}){const page=content[type];return <><section className="page-hero"><p className="eyebrow">TWS · The Work Suites</p><h1>{page.title}</h1><p>{page.intro}</p></section><section className="section policy-page">{type==='faq'?<FAQAccordion items={page.sections}/>:page.sections.map(([title,copy])=><article key={title}><h2>{title}</h2><p>{copy}</p></article>)}</section></>}
