import{useState}from'react';
import{Minus,Plus}from'lucide-react';

const content={
  faq:{title:'Frequently asked questions',intro:'Clear answers before you book.',sections:[['How does booking work?','Choose a workspace and time, sign in, and confirm your booking. Online payment is currently disabled, so TWS opens a prepared WhatsApp message and the office team contacts you to complete payment.'],['Can I cancel?','Cancellation requests are accepted until 48 hours before the booking starts and are reviewed by the TWS office team.'],['Are prices inclusive of GST?','The booking summary shows the workspace price and applicable GST separately before you confirm.'],['How are refunds handled?','When a cancellation is approved, any amount already paid directly to TWS is handled by the office team and the booking status is updated in your account.'],['Can teams book private spaces?','Yes. Private cabins, meeting rooms and the conference room support team reservations.']]},
  privacy:{title:'Privacy policy',intro:'How TWS · The Work Suites handles account and booking information.',sections:[['Information we collect','We store the account, contact, billing and booking information needed to operate the service. Online card and UPI payment details are not collected while online payment is disabled.'],['How we use it','Information is used for authentication, reservations, invoices, support, security, service notifications and legal compliance.'],['Retention and security','Access is role-controlled, passwords are salted and hashed, and sensitive operations are audited. Information is retained only as needed to provide the service and meet legal obligations.'],['Your choices','Customers may update profile information and request account-data assistance through the published support contact.']]},
  terms:{title:'Booking terms',intro:'The operating rules for reservations and workspace use.',sections:[['Reservations','A booking is recorded after you confirm it online. Online payment is currently disabled, and the TWS office team contacts you directly to complete payment and finalise the reservation.'],['Cancellations','Cancellation requests must be submitted at least 48 hours before the booking starts. The TWS office team reviews each request and confirms any applicable amount and timeline directly with the customer.'],['Workspace use','Customers must follow site safety, access, conduct and acceptable-use rules. Access may be refused for misuse or fraudulent activity.'],['Contact','For booking, payment, cancellation or account help, use the website enquiry form or contact TWS on +91 77788 86839.']]}
};
function FAQAccordion({items}){const[open,setOpen]=useState(0);return <div className="faq-accordion">{items.map(([title,copy],index)=>{const expanded=open===index;return <article className={expanded?'open':''} key={title}><button onClick={()=>setOpen(expanded?-1:index)} aria-expanded={expanded}><span>{title}</span><i>{expanded?<Minus/>:<Plus/>}</i></button><div className="faq-answer" aria-hidden={!expanded}><p>{copy}</p></div></article>})}</div>}
export default function InfoPage({type}){const page=content[type];return <><section className="page-hero"><p className="eyebrow">TWS · The Work Suites</p><h1>{page.title}</h1><p>{page.intro}</p></section><section className="section policy-page">{type==='faq'?<FAQAccordion items={page.sections}/>:page.sections.map(([title,copy])=><article key={title}><h2>{title}</h2><p>{copy}</p></article>)}</section></>}
