import{useEffect,useState}from'react';
import{motion}from'framer-motion';
import{ArrowRight,Check,Clock3,Mail,MapPin,MessageCircle,Phone}from'lucide-react';
import{Link}from'react-router-dom';
import{api,money}from'../api';
import{useSiteContent}from'../siteContent';
import{pricingPlans}from'../pricingData';

const reveal={initial:{opacity:0,y:24},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.2},transition:{duration:.55,ease:[.16,1,.3,1]}};

export function Pricing(){const[items,setItems]=useState([]);useEffect(()=>{api('/workspaces').then(result=>setItems(result.items||[])).catch(()=>{})},[]);const shown=pricingPlans.map(plan=>({...plan,_id:items.find(item=>item.type===plan.type&&item.status==='active')?._id}));return <><section className="page-hero pricing-hero"><p className="eyebrow">Confirmed workspace prices</p><h1>Simple plans.<br/><em>Clear pricing.</em></h1><p>These are the confirmed TWS prices. Online payment is currently disabled; booking confirmation is handled by the TWS team.</p></section><section className="section pricing-page"><div className="pricing-grid">{shown.map((plan,index)=><motion.article {...reveal} transition={{...reveal.transition,delay:index*.08}} key={plan.name}><span>0{index+1}</span><h2>{plan.name}</h2><p>{plan.copy}</p><div className="plan-rates"><div><small>Price</small><strong>{money(plan.price)} <small>/ {plan.unit}</small></strong></div></div><ul>{plan.features.map(item=><li key={item}><Check/>{item}</li>)}</ul><Link className="btn btn-dark" to={plan._id?`/book?workspace=${plan._id}`:'/book'}>Check availability <ArrowRight/></Link></motion.article>)}</div><motion.div className="pricing-note lease-note" {...reveal}><div><p className="eyebrow">Included for every workspace</p><h2>Two complimentary private phone booths.</h2><p>The booths are free to use and are not charged as a separate booking.</p></div><Link className="btn btn-accent" to="/book?mode=lease">Request a lease call</Link></motion.div></section></>}

export function Contact(){const content=useSiteContent('contact',{title:'Easy to find. Easy to work from.',body:'Bannerghatta Main Road, Kothnur, Kalena Agrahara, Bengaluru 560083.'}),email=import.meta.env.VITE_BUSINESS_EMAIL,phone=import.meta.env.VITE_BUSINESS_PHONE||'+91 77788 86839',hours=import.meta.env.VITE_BUSINESS_HOURS;return <><section className="page-hero contact-hero"><p className="eyebrow">Visit TWS</p><h1>{content.title}</h1><p>{content.body}</p></section><section className="section contact-page"><motion.div className="contact-details" {...reveal}><article><MapPin/><span>Exact location</span><strong>Bannerghatta Main Road<br/>Kothnur, Kalena Agrahara<br/>Bengaluru, Karnataka 560083<br/>Beside Carmel Academy ICSE School</strong></article><article><Clock3/><span>Visit timings</span><strong>{hours||'Please request a call to confirm current operating hours.'}</strong></article><article><Mail/><span>Email</span><strong>{email||'Use the enquiry form for an email response.'}</strong></article><article><Phone/><span>Phone</span><strong>{phone}</strong></article></motion.div><motion.div className="contact-map-art" {...reveal}><div className="map-grid"/><i/><b>TWS</b><span>Kothnur · Kalena Agrahara</span></motion.div><motion.div className="contact-actions" {...reveal}><div><MessageCircle/><div><h2>Want to purchase or lease a space?</h2><p>Call or WhatsApp TWS, or check current online availability.</p></div></div><a className="btn btn-accent" href="https://wa.me/917778886839" target="_blank" rel="noreferrer">WhatsApp TWS <ArrowRight/></a></motion.div></section></>}
