import{useEffect,useState}from'react';
import{motion}from'framer-motion';
import{ArrowRight,Check,Clock3,Mail,MapPin,MessageCircle,Phone}from'lucide-react';
import{Link}from'react-router-dom';
import{api,money}from'../api';
import{useSiteContent}from'../siteContent';

const plans=[
 {type:'hot_desk',name:'Hot / Flexi Desk',pricing:{monthly:7999},copy:'A flexible desk for professionals who want an easy place to work.',features:['Flexible seating','Shared work area','Phone booths included','Single-floor facility']},
 {type:'dedicated_desk',name:'Dedicated Desk',pricing:{monthly:8999},copy:'Your own dedicated desk in a professionally managed shared workspace.',features:['Dedicated workstation','Shared facilities','Phone booths included','Single-floor facility']},
 {type:'private_cabin',name:'Private Cabin',pricing:{monthly:9999},copy:'A private workspace for individuals and teams.',features:['3, 4 and 6-seater options','Private access','Team seating','Phone booths included']},
 {type:'day_package',name:'Day Package',pricing:{daily:500},copy:'Use the workspace for one working day without a monthly commitment.',features:['One-day access','Shared work area','Common amenities','Phone booths included']}
];

const reveal={initial:{opacity:0,y:24},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.2},transition:{duration:.55,ease:[.16,1,.3,1]}};

export function Pricing(){const[items,setItems]=useState([]);useEffect(()=>{api('/workspaces').then(result=>setItems(result.items||[])).catch(()=>{})},[]);const shown=plans.map(plan=>{const live=items.find(item=>item.type===plan.type&&item.status==='active');return live?{...plan,_id:live._id}:plan});return <><section className="page-hero pricing-hero"><p className="eyebrow">Confirmed workspace prices</p><h1>Simple plans.<br/><em>Clear monthly pricing.</em></h1><p>Choose a monthly workspace or a ₹500 day package. GST and the final payable amount appear before confirmation.</p></section><section className="section pricing-page"><div className="pricing-grid">{shown.map((plan,index)=><motion.article {...reveal} transition={{...reveal.transition,delay:index*.08}} key={plan.name}><span>0{index+1}</span><h2>{plan.name}</h2><p>{plan.copy}</p><div className="plan-rates">{Object.entries(plan.pricing).map(([unit,value])=><div key={unit}><small>Per {unit.replace('ly','')}</small><strong>{money(value)}</strong></div>)}</div><ul>{plan.features.map(item=><li key={item}><Check/>{item}</li>)}</ul><Link className="btn btn-dark" to={plan._id?`/book?workspace=${plan._id}`:'/book'}>Check availability <ArrowRight/></Link></motion.article>)}</div><motion.div className="pricing-note lease-note" {...reveal}><div><p className="eyebrow">Monthly or yearly lease</p><h2>Need a workspace longer? Submit a lease request from the normal booking page.</h2><p>No separate lease page and no account required to submit the request.</p></div><Link className="btn btn-accent" to="/book?mode=lease">View lease option</Link></motion.div></section></>}

export function Contact(){const content=useSiteContent('contact',{title:'Easy to find. Easy to work from.',body:'Bannerghatta Main Road, Kothnur, Kalena Agrahara, Bengaluru 560083.'}),email=import.meta.env.VITE_BUSINESS_EMAIL,phone=import.meta.env.VITE_BUSINESS_PHONE,hours=import.meta.env.VITE_BUSINESS_HOURS;return <><section className="page-hero contact-hero"><p className="eyebrow">Visit TWS</p><h1>{content.title}</h1><p>{content.body}</p></section><section className="section contact-page"><motion.div className="contact-details" {...reveal}><article><MapPin/><span>Exact location</span><strong>Bannerghatta Main Road<br/>Kothnur, Kalena Agrahara<br/>Bengaluru, Karnataka 560083<br/>Beside Carmel Academy ICSE School</strong></article><article><Clock3/><span>Visit timings</span><strong>{hours||'Please request a call to confirm current operating hours.'}</strong></article><article><Mail/><span>Email</span><strong>{email||'Use the enquiry form for an email response.'}</strong></article><article><Phone/><span>Phone</span><strong>{phone||'Request a callback—no account required.'}</strong></article></motion.div><motion.div className="contact-map-art" {...reveal}><div className="map-grid"/><i/><b>TWS</b><span>Kothnur · Kalena Agrahara</span></motion.div><motion.div className="contact-actions" {...reveal}><div><MessageCircle/><div><h2>Want to purchase or lease a space?</h2><p>Request a call without creating an account, or check online availability.</p></div></div><Link className="btn btn-accent" to="/home#enquire">Request a call <ArrowRight/></Link></motion.div></section></>}
