import{motion}from'framer-motion';
import{ArrowUpRight,MapPin,Users}from'lucide-react';
import{useNavigate}from'react-router-dom';
import{money}from'../api';
const labels={hot_desk:'Flexi desk',dedicated_desk:'Dedicated desk',private_cabin:'Private cabin',meeting_room:'Meeting room',conference_room:'Conference room',phone_booth:'Phone booth'};
const fallbackByType={hot_desk:'/images/workspace-flexi.webp',dedicated_desk:'/images/workspace-dedicated.webp',private_cabin:'/images/tws-private-cabin.webp',meeting_room:'/images/workspace-meeting.webp',conference_room:'/images/tws-conference-01.webp',phone_booth:'/images/tws-passage-01.webp'};
const replacedImages={hot_desk:'/images/tws-passage-03.webp',dedicated_desk:'/images/tws-print-area.webp',meeting_room:'/images/tws-cafe-04.webp'};
export const workspaceImageFor=item=>!item?.image||item.image===replacedImages[item.type]?fallbackByType[item?.type]||'/images/tws-foyer-01.webp':item.image;
const capacityLabel=item=>item.catalogCabinGroup?'Multiple cabin sizes available':item.type==='meeting_room'?`10 people per room${item.unitCount?` · ${item.bookableUnitCount} available`:''}`:item.type==='conference_room'?'Approximately 20–25 people':item.type==='phone_booth'?'2 complimentary booths':item.type==='private_cabin'?`${item.capacity} people · ${item.bookableUnitCount} ${item.derivedOption?'configuration':'cabin'}${item.bookableUnitCount===1?'':'s'} available`:item.unitCount?`${item.bookableUnitCount} of ${item.unitCount} seats available`:item.capacity?`${item.capacity} ${item.capacity===1?'person':'people'}`:'Availability confirmed by TWS';
export function WorkspaceCard({item,index=0}){const navigate=useNavigate(),rates=Object.entries(item.pricing||{}).filter(([,value])=>value),[unit,start]=rates.sort((a,b)=>a[1]-b[1])[0]||['',0],unitName={hourly:'hour',daily:'day',weekly:'week',monthly:'month'}[unit]||'',open=()=>navigate(`/book?workspace=${item.bookingWorkspaceId||item._id}${item.type==='private_cabin'?`&cabin=${item.capacity}`:''}`),capacity=capacityLabel(item),label=item.catalogCabinGroup?'Private cabins':labels[item.type]||item.type;return <motion.article className="workspace-card workspace-card-clickable" role="link" tabIndex={0} aria-label={`See available options for ${item.name}`} onClick={open} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();open()}}} initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.06}} whileHover={{y:-7}}><div className="workspace-photo"><img src={workspaceImageFor(item)} loading="lazy" decoding="async" alt={`${item.name} workspace`}/><span className={`availability ${item.status}`}>{item.status==='active'?'Available':item.status}</span><span className="card-count">0{index+1}</span></div><div className="workspace-card-body"><p className="eyebrow">{label}</p><h3>{item.name}</h3><p>{item.description}</p><div className="workspace-meta"><span><Users size={16}/>{capacity}</span><span><MapPin size={16}/>{item.zone||'TWS Bengaluru'}</span></div><div className="card-foot"><div><small>{item.type==='private_cabin'?'₹9,999 / desk':'From'}</small><strong>{money(start)}<em>{unitName?` / ${unitName}`:''}</em></strong></div><span className="round-button" aria-hidden="true"><ArrowUpRight/></span></div></div></motion.article>}
